import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from "./providers/ReduxProvider";

const CirceRounded = localFont({
	src: [
		{
			path: "../../public/CirceRounded-Thin.otf",
			weight: "100",
		},
		{
			path: "../../public/CirceRounded-ExtraLight.otf",
			weight: "200",
		},
		{
			path: "../../public/CirceRounded-Light.otf",
			weight: "300",
		},
		{
			path: "../../public/CirceRounded-Regular.otf",
			weight: "400",
		},
		{
			path: "../../public/CirceRounded-Bold.otf",
			weight: "700",
		},
		{
			path: "../../public/CirceRounded-ExtraBold.otf",
			weight: "800",
		},
	],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ReduxProvider>
				<body className={CirceRounded.className}>{children}</body>
			</ReduxProvider>
		</html>
	);
}
